version: '3.3'
services:
  backend:
    build: 
      context: backend/
      dockerfile: Dockerfile
    # init: true
    networks:
    - ss-app
  frontend:
    build: 
      context: frontend/
      dockerfile: Dockerfile
    # init: true
    networks:
    - ss-app
    ports:
    - "9091-9095:8080"
    depends_on:
    - backend
    # application:
    # name: ss-app
  db:
    image: mysql:5.7.22
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - ss-app
    volumes:
      - .dbdata:/var/lib/mysql
volumes:
  dbdata:
networks:
  ss-app:
    external: true
